repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: no-commit-to-branch
        args: [--branch, main]
-   repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
    -   id: gradle-task 
        args: ['--wrapper', 'checkstyle']
        verbose: true